# Generated by Django 4.1.7 on 2023-09-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='descp',
        ),
    ]
